config/routes.rb
Rails.application.routes.draw do

  resources :preferences
  resources :measure_names
  resources :measure_units
  resources :measurements

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    authenticated :user do
      root :to => redirect('/measurements'), as: :authenticated_root
    end
    unauthenticated do
      root :to => redirect("/users/sign_in"), as: :unauthenticated_root
    end
  end
  root :to => 'measurements#index'

  get 'list', :to => 'measurements#list'

  match ':controller(/:action(/:id))', :via => [:get, :post]

  get 'users/measurements', :to => 'measurements#index'
  get 'users/measurements/list', :to => 'measurements#list'
  get 'users/measure_names', :to => 'measure_names#index'
  get 'users/measure_units', :to => 'measure_units#index'

end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :measure_name
  belongs_to :user
  belongs_to :measure_unit
  accepts_nested_attributes_for :measure_name
  accepts_nested_attributes_for :measure_unit
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
  end

  # GET /preferences/new
  def new
    @preference = Preference.new
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(preference_params)
    @preference.user = current_user

    respond_to do |format|
      if @preference.save
        format.html { redirect_to @preference, notice: 'Preference was successfully created.' }
        format.json { render :show, status: :created, location: @preference }
      else
        format.html { render :new }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferences/1
  # PATCH/PUT /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        format.html { redirect_to @preference, notice: 'Preference was successfully updated.' }
        format.json { render :show, status: :ok, location: @preference }
      else
        format.html { render :edit }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference.destroy
    respond_to do |format|
      format.html { redirect_to preferences_url, notice: 'Preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:measure_name_id, :user_id, :position, :measure_unit_id, :frequency)
    end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/_form.html.erb
<%= form_for @preference, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :position, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :position, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :frequency, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :frequency, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  preferences_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Preference %></h1>
</div>
<%= render :partial => 'form' %>

app/views/preferences/index.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => Preference %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:frequency) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @preferences.each do |preference| %>
      <tr>
        <td><%= preference.id %></td>
        <td><%= preference.position %></td>
        <td><%= preference.frequency %></td>
        <td><%=l preference.created_at, format: :long %></td>
        <td>
          <%= link_to preference_path(preference), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to preference_path(preference), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_preference_path,
            :class => 'btn btn-primary' %>

app/views/preferences/new.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Preference %></h1>
</div>
<%= render :partial => 'form' %>

app/views/preferences/show.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => Preference %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:position) %></dt>
      <dd><pre class="prettyprint"><%= @preference.position %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:frequency) %></dt>
      <dd><pre class="prettyprint"><%= @preference.frequency %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              preferences_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_preference_path(@preference), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              preference_path(@preference),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>