config/routes.rb
Rails.application.routes.draw do

  resources :preferences
  resources :measure_names
  resources :measure_units
  resources :measurements

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    authenticated :user do
      root :to => redirect('/measurements'), as: :authenticated_root
    end
    unauthenticated do
      root :to => redirect("/users/sign_in"), as: :unauthenticated_root
    end
  end
  root :to => 'measurements#index'

  get 'list', :to => 'measurements#list'

  match ':controller(/:action(/:id))', :via => [:get, :post]

  get 'users/measurements', :to => 'measurements#index'
  get 'users/measurements/list', :to => 'measurements#list'
  get 'users/measure_names', :to => 'measure_names#index'
  get 'users/measure_units', :to => 'measure_units#index'

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
	belongs_to :user
	belongs_to :measure_name
	belongs_to :measure_unit
	# has_one :measure_unit, :through => :measure_name
	accepts_nested_attributes_for :measure_name
	accepts_nested_attributes_for :measure_unit
	acts_as_taggable
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:list, :show, :new, :edit, :create, :update, :destroy]

  before_action :set_measurement, only: [:show, :edit, :update, :destroy]
  before_action :find_measure_name_id
  before_action :find_measure_unit_id

  def list
    @measurements = Measurement.all.order('happened_at DESC')
    @measure_names = MeasureName.all.order('name ASC')
    @user = current_user
    @measurements_by_user = Measurement.order('happened_at DESC').where(:user_id => current_user.id)
  end
  
  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all.order('happened_at DESC')
    @measure_names = MeasureName.all.order('name ASC')
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
    @measure_names = MeasureName.all.order('name ASC')
    @measure_units = MeasureUnit.all.order('name ASC')
  end

  # GET /measurements/1/edit
  def edit
    @measure_names = MeasureName.all
    @measure_units = MeasureUnit.all
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(measurement_params)
    @measurement.user = current_user

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render :show, status: :created, location: @measurement }
      else
        format.html { render :new }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @measurement }
      else
        format.html { render :edit }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url, notice: 'Measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      if params[:id]
        @measurement = Measurement.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:altitude, :latitude, :longitude, :happened_at, :user_id, :measure_name_id,
        :measure_unit_id, :value, :notes, :tag_list)
    end

    def find_measure_name_id
      if params[:measure_name_id]
        @measure_name_name = MeasureName.find(params[:measure_name_id]).name
        @measure_name_id = MeasureName.find(params[:measure_name_id]).id
      end
    end

    def find_measure_unit_id
      if params[:measure_unit_id]
        @measure_unit_name = MeasureUnit.find(params[:measure_unit_id]).name
        @measure_unit_id = MeasureUnit.find(params[:measure_unit_id]).id
      end
    end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<%= form_for @measurement, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <!-- <div class="form-group"> -->
    <%# f.label :altitude, :class => 'control-label col-md-2' %>
    <!-- <div class="col-md-10"> -->
      <%= f.hidden_field :altitude, :placeholder => "(Not provided by your browser)", :class => 'text-field form-control' %>
    <!-- </div>
  </div>
  <div class="form-group"> -->
    <%# f.label :latitude, :class => 'control-label col-md-2' %>
    <!-- <div class="col-md-10"> -->
      <%= f.hidden_field :latitude, :class => 'text-field form-control' %>
<!--     </div>
  </div>
  <div class="form-group"> -->
    <%# f.label :longitude, :class => 'control-label col-md-2' %>
<!--     <div class="col-md-10"> -->
      <%= f.hidden_field :longitude, :class => 'text-field form-control' %>
<!--     </div>
  </div> -->
  <div class="form-group">
    <%= f.label :happened_at, 'At', :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :happened_at, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :measure_name_id, 'Activity', :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.select :measure_name_id, @measure_names.map {|m| [m.name, m.id]}, :include_blank => "Select One", :selected => params[:measure_name_id], :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :measure_unit_id, 'Units', :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.select :measure_unit_id, @measure_units.map {|m| [m.name, m.id]}, :include_blank => "Select One", :selected => @measure_names.find(params[:measure_name_id]).measure_unit_id, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :value, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :value, :placeholder => "21.2", autofocus: true, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :notes, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :notes, :placeholder => "i.e., Ate a late dinner last night, had trouble sleeping", :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tag_list, "Tags", :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :tag_list, :placeholder => "tag, tag, tag...", :class => 'text-field form-control' %>
    </div>
  </div>

  <!-- set default bool value to "true" if unit of measure passed in params is a bool -->
        <% if params[:measure_unit_id] == "2" %>
          <% @val = "1" %>
        <% end %>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  measurements_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Measurement %></h1>
</div>
<%= render :partial => 'form' %>

app/views/measurements/index.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => 'Record Activities' %></h1>
</div>

<ul class="list-inline">
  <% @measure_names.each do |m| %>
  <li>
    <%= link_to t(m.name, :default => t(m.name)),
      new_measurement_path(:measure_name_id => m.id, :measure_unit_id => @measure_unit_id),
      :class => 'btn btn-primary josiah'%>
  </li>
  <% end %>
</ul>

<div>
  <p>
    Click any button to record a new measurement.
  </p>
</div>


<!--  :measure_unit_id => @preferences.measure_unit_id -->

app/views/measurements/list.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Activity Journal" %></h1>
</div>
  <ul>
    <% @measurements_by_user.each do |measurement| %>
        <li>
          <strong><%= @user.first_name %></strong> recorded the activity <strong><%= measurement.measure_name.name %></strong> <% if measurement.measure_unit.abbreviation != "bool" %> with a value of <strong><%= measurement.value %></strong> <%= measurement.measure_unit.abbreviation %><% else %><% end %> <em>on <%=l measurement.happened_at, format: "%A, %-m/%-d/%y, at %l:%M %P" %></em>

          <% if measurement.tag_list.any? %><span class="tab"><br /><em>Tags: <%= measurement.tag_list %></em></span><% else %><% end %>
          <% if measurement.notes != "" %><span class="tab"><br /><em>Notes: <%= measurement.notes %></em></span><% else %><% end %>
        </li>
    <% end %>
  </ul>

<%= link_to 'Record a New Activity',
            root_path,
            :class => 'btn btn-primary' %>

app/views/measurements/listtable.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => Measurement %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:altitude) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:happened_at) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:notes) %></th>
      <th><%= model_class.human_attribute_name(:measure_unit_name) %></th>
      <th><%= model_class.human_attribute_name(:measure_name_name) %></th>
      <th><%= model_class.human_attribute_name(:tag_list) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @measurements.each do |measurement| %>
      <tr>
        <td><%= measurement.id %></td>
        <td><%= measurement.altitude %></td>
        <td><%= measurement.latitude %></td>
        <td><%= measurement.longitude %></td>
        <td><%=l measurement.happened_at, format: :long %></td>
        <td><%= measurement.value %></td>
        <td><%= measurement.notes %></td>
        <td><%= measurement.measure_unit.name %></td>
        <td><%= measurement.measure_name.name %></td>
        <td><%= measurement.tag_list %></td>
        <td><%=l measurement.created_at, format: :long %></td>
        <td>
          <%= link_to measurement_path(measurement), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to measurement_path(measurement), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New',
            root_path,
            :class => 'btn btn-primary' %>

app/views/measurements/new.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New Record: ' + @measure_name_name.titleize ], :model => Measurement %></h1>
</div>
<%= render :partial => 'form' %>

<script>
var alt = document.getElementById("measurement_altitude");
var lat = document.getElementById("measurement_latitude");
var lon = document.getElementById("measurement_longitude");
var result = document.getElementById("result");
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        // result.innerHTML = "Geolocation is not supported by this browser.";
    }
}
function showPosition(position) {
    if (position.coords.latitude != null) {
    	lat.value = position.coords.latitude;
    } else {lat.value = ""}

    if (position.coords.longitude != null) {
    	lon.value = position.coords.longitude;
	} else {lon.value = ""}
    
    if (position.coords.altitude != null) {
    	alt.value = position.coords.altitude / 3.28084; // convert meters to feet
    } else { alt.value = "";}    
}
getLocation();
</script>

app/views/measurements/show.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => Measurement %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:altitude) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.altitude %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:latitude) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.latitude %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:longitude) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.longitude %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:happened_at) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.happened_at %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:value) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.value %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:notes) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.notes %></pre></dd>

      <dt class="label label-default"><%= model_class.human_attribute_name(:measure_unit_name) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.measure_unit.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:measure_name_name) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.measure_name.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:tag_list) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.tag_list %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              measurements_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_measurement_path(@measurement, :measure_name_id => @measurement.measure_name.id, :measure_unit_id => @measurement.measure_unit.id), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              measurement_path(@measurement),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>